export const roleArray = [
	{
		name: 'Héro',
		text: 'Avec 16 en Force, 14 en Vigueur et 12 en Endurance, le héro est la classe idéale si vous souhaitez commencer le jeu sans vous prendre trop la tête avec tout ce qui est magie, incantation ou autre et que tout ce qui vous intéresse, c’est taper comme un sourd sans être trop vulnérable. C’est effectivement la classe avec la stat de Force la plus élevée, et la seconde stat de Vigueur la plus élevée, ce qui vous permettra de faire de bons dégâts tout en ayant une certaine survivabilité si vous prenez des coups. ',
		image: './src/assets/hero.png',
		niveau: 'Niveau: 7',
		vigueur: 'Vigueur: 14',
		esprit: 'Esprit: 9',
		endurance: 'Endurance: 12',
		force: 'Force: 16',
		dextérité: 'Dextérité: 9',
		intelligence: 'Inteligence: 7',
		foi: 'Foi: 8',
		esotérisme: 'Ésotérisme: 11',
	},
	{
		name: 'Bandit',
		text: 'Deux choses permettent de véritablement distinguer le bandit : l’accès à un Arc dès le début du jeu, et sa stat d’Esotérisme qui est la plus haute de toutes les classes (14). Avec une stat de Dextérité qui n’est pas à négliger (13), le bandit peut se jouer de la manière suivante : affaiblir l’ennemi de loin avec une arme à distance (et même pourquoi pas, des sorts) avant de l’achever au corps-à-corps. La stat d’Esotérisme vous permettra alors d’obtenir beaucoup plus de loot que la normale, ce qui vous permettra ensuite de crafter encore plus d’objets pour attaquer vos ennemis à distances et les approcher de manière subtile.',
		image: './src/assets/bandit.png',
		niveau: 'Niveau: 5',
		vigueur: 'Vigueur: 10',
		esprit: 'Esprit: 11',
		endurance: 'Endurance: 10',
		force: 'Force: 9',
		dextérité: 'Dextérité: 13',
		intelligence: 'Inteligence: 9',
		foi: 'Foi: 8',
		esotérisme: 'Ésotérisme: 14',
	},
	{
		name: 'Astrologue',
		text: 'L’Astrologue est tout simplement le mage par excellence : ses stats d’Esprit (15) et d’Intelligence (16) sont les plus hautes de toutes les classes de départ, ce qui en fait le lanceur de sort par excellence. Il commence également avec une épée au cas où vous n’avez plus de PC, mais ne vous attendez pas à faire des miracles avec car avec une Vigueur de 9 (la plus faible de toutes les classes de départ), le moindre coup vous fera très mal.',
		image: './src/assets/astrologue.png',
		niveau: 'Niveau: 6',
		vigueur: 'Vigueur: 9',
		esprit: 'Esprit: 15',
		endurance: 'Endurance: 9',
		force: 'Force: 8',
		dextérité: 'Dextérité: 12',
		intelligence: 'Inteligence: 16',
		foi: 'Foi: 7',
		esotérisme: 'Ésotérisme: 9',
	},
	{
		name: 'Guerrier',
		text: 'Contrairement à ce que le nom peut laisser croire, le guerrier ne mise pas tout sur la Force mais sur la Dextérité qui est la plus haute de toutes les classes (16). Le Guerrier est donc la classe par excellence si vous voulez essayez un build Dextérité et que vous êtes plus du genre à asséner plusieurs petits coups rapides plutôt qu’un grand coup lent mais dévastateur.',
		image: './src/assets/guerrier.png',
		niveau: 'Niveau: 8',
		vigueur: 'Vigueur: 11',
		esprit: 'Esprit: 12',
		endurance: 'Endurance: 11',
		force: 'Force: 10',
		dextérité: 'Dextérité: 16',
		intelligence: 'Inteligence: 10',
		foi: 'Foi: 8',
		esotérisme: 'Ésotérisme: 9',
	},
	{
		name: 'Prisonnier',
		text: 'Le prisonnier est un build hybride Dextérité / Intelligence (14 dans les deux stats). Cela peut sembler un peu random, mais les deux stats ont une synergie très intéressante. En effet, dans Elden Ring, la Dextérité permet de lancer plus rapidement vos sorts ce qui fait qu’en montant la Dextérité, vous augmentez non seulement vos capacités physiques, mais également d’une certaine façon vos capacités magiques. Vous aurez donc à la fois des solutions au corps-à-corps, mais aussi à distance grâce à vos sorts.',
		image: './src/assets/prisonnier.png',
		niveau: 'Niveau: 9',
		vigueur: 'Vigueur: 11',
		esprit: 'Esprit: 12',
		endurance: 'Endurance: 11',
		force: 'Force: 11',
		dextérité: 'Dextérité: 14',
		intelligence: 'Inteligence: 14',
		foi: 'Foi: 6',
		esotérisme: 'Ésotérisme: 9',
	},
	{
		name: 'Confesseur',
		text: 'Le confesseur est l’une des deux classes qui privilégie la Foi comme stat principale (14). Ceci étant dit, contrairement au prophète, le confesseur est beaucoup moins vulnérable au corps-à-corps et n’est pas encore totalement spécialisé dans les incantations. C’est donc la classe parfaite si vous souhaitez faire un build Dextérité / Foi (voire Force / Foi) où la Dextérité sera votre principale source de dégâts, avec quelques Incantations pour vous aider en support.',
		image: './src/assets/confesseur.png',
		niveau: 'Niveau: 10',
		vigueur: 'Vigueur: 10',
		esprit: 'Esprit: 13',
		endurance: 'Endurance: 10',
		force: 'Force: 12',
		dextérité: 'Dextérité: 12',
		intelligence: 'Inteligence: 9',
		foi: 'Foi: 14',
		esotérisme: 'Ésotérisme: 9',
	},
	{
		name: 'Indigent',
		text: 'C’est la traditionnelle classe qui commence au niveau 1. Avec toutes les stats à 10, puisqu’elle commence au niveau 1, c’est la classe qui permet la plus grande liberté dans la customisation de vos stats. Ainsi, si vous connaissez déjà précisément la distribution de stats que vous souhaitez avoir sur votre personnage, c’est la classe à prendre. Dans les faits, c’est surtout pratique pour les builds PvP où vous avez besoin d’avoir certaines stats sans dépasser un certain niveau. Pour le PvE, c’est un peu moins vital mais c’est toujours agréable d’avoir un total control sur la répartition des stats.',
		image: './src/assets/indigent.png',
		niveau: 'Niveau: 1',
		vigueur: 'Vigueur: 10',
		esprit: 'Esprit: 10',
		endurance: 'Endurance: 10',
		force: 'Force: 10',
		dextérité: 'Dextérité: 10',
		intelligence: 'Inteligence: 10',
		foi: 'Foi: 10',
		esotérisme: 'Ésotérisme: 10',
	},
	{
		name: 'Vagabond',
		text: 'Avec 14 en Force et 13 en Dextérité, le Vagabond est parfait pour faire un build « qualité », c’est-à-dire un build Force / Dextérité. C’est également la classe avec la Vigueur la plus élevée (15). La Force permettant d’équiper des armures plus lourdes, cela en fait donc une excellente classe physique puisqu’elle assure une certaine survivabilité tout en donnant des options offensives non négligeables.',
		image: './src/assets/vagabond.png',
		niveau: 'Niveau: 9',
		vigueur: 'Vigueur: 15',
		esprit: 'Esprit: 10',
		endurance: 'Endurance: 11',
		force: 'Force: 14',
		dextérité: 'Dextérité: 13',
		intelligence: 'Inteligence: 9',
		foi: 'Foi: 9',
		esotérisme: 'Ésotérisme: 7',
	},
	{
		name: 'Prophète',
		text: 'A l’inverse du confesseur, avec un Esprit de 13 et une Foi de 16 (la plus haute de toutes les classes) le prophète est déjà bien ancré dans un archétype : celui du lanceur d’incantation à distance. Elden Ring propose beaucoup plus de solutions offensives pour les builds Foi que les anciens Souls où les Miracles étaient principalement des sorts de support ou de soin. Le Prophète commence avec l’Incantation Soin, ce qui est très pratique au début du jeu pour contourner la limitation de soin disponible.',
		image: './src/assets/prophete.png',
		niveau: 'Niveau: 7',
		vigueur: 'Vigueur: 10',
		esprit: 'Esprit: 14',
		endurance: 'Endurance: 8',
		force: 'Force: 12',
		dextérité: 'Dextérité: 8',
		intelligence: 'Inteligence: 7',
		foi: 'Foi: 16',
		esotérisme: 'Ésotérisme: 11',
	},
	{
		name: 'Samouraï',
		text: 'Avec une stat d’Endurance la plus élevée de toutes les classes (13) et une Dextérité très élevée (15), le Samurai excelle également dans l’art du « porter 100 petits coups plus qu’un seul dévastateur ». Avec beaucoup plus d’endurance que le guerrier, et commençant avec des armes qui ont déjà une compétence d’arme, le Samurai correspondra surtout à ceux qui aiment les personnages rapides et techniques à utiliser. ',
		image: './src/assets/samourai.png',
		niveau: 'Niveau: 9',
		vigueur: 'Vigueur: 12',
		esprit: 'Esprit: 11',
		endurance: 'Endurance: 13',
		force: 'Force: 12',
		dextérité: 'Dextérité: 15',
		intelligence: 'Inteligence: 9',
		foi: 'Foi: 8',
		esotérisme: 'Ésotérisme: 8',
	},
];
export default roleArray;
